export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const DELETE_ITEM = "DELETE_ITEM";
export const CLEAR_CART = "CLEAR_CART"